---
title: "Metadata and Data Preprocessing"
author: "Author: Asger Svenning<br>"
date: "Date: `r Sys.Date()`"
output: 
  bookdown::github_document2:
    toc: true
    toc_title: "Table of Contents"
    number_sections: true
    keep_tex: true
always_allow_html: true
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'README.md')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, eval = F, fig.path = "readme_files/chunk_figures/")

library(tidyverse)
library(magrittr)
library(extrafont)
library(forcats)
library(kableExtra)
library(exifr)
library(lubridate)
```

\newpage

# Data file path indexing

In order to construct a reproducible, first we must index the metadata and data filepaths. This can be done using the base *R* functions `list.dir` and `list.files`.

```{r, eval = T}
data_dir <- "../Raw data/Init"

index <- tibble(dir = list.dirs(data_dir)) %>% 
  mutate(file = map(dir, list.files)) %>% 
  unnest(file) %>% 
  filter(str_detect(file,"\\..{1,4}")) %>% 
  mutate(relative = map2_chr(dir,file,~paste0(.x,"/",.y)),
         absolute = R.utils::getAbsolutePath(relative),
         src = str_remove(dir, paste0(data_dir)) %>% 
           str_remove("^/") %>% 
           replace(which(. == ""), "Root"))

index %>% 
  mutate(Filetype = str_extract(file,"(?<=\\.).{1,4}$") %>% 
           factor %>% 
           factor(levels = sort(levels(.)))) %>% 
  filter(Filetype != "db") %>% 
  mutate(Filetype = droplevels(Filetype)) %>% 
  count(src,Filetype) %>%
  complete(src,Filetype,fill=list(n = 0)) %>% 
  # mutate(src = paste0('<p  style="font-weight: normal;">', src, "</p>")) %>% 
  pivot_wider(Filetype,names_from=src,values_from=n) %>% 
  rename("<b>Filetype</b>" = Filetype) %>%
  kable("html",
        align="c", 
        caption = "Filetype Counts in the Raw File Index", 
        escape=F) %>% 
  kable_styling(full_width = T) %>%
  row_spec(0, extra_css = "font-weight: normal;") %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2:4, width = "3cm") %>% 
  add_header_above(c("","Subdirectory" = 3), bold = T)
```

Next I will attempt to extract the file metadata using the R package `exifr` which is a R wrapper around the file metadata software `exiftools`.

```{r}
library(furrr)

read_exif_long <- function(...) {
  read_exif(...) %>% 
    mutate(across(everything(), as.character)) %>% 
    select(!SourceFile) %>% 
    pivot_longer(everything(),names_to="Tag",values_to="Metadata")
}

plan("multisession")
index_meta <- index %>% 
  select(absolute,src) %>% 
  mutate(fid = row_number(),
         exif = future_map(absolute, read_exif_long, tags = c("FileCreateDate","FileSize", "CreateDate","GPSDateTime"))) %>% 
  unnest(exif)
plan("sequential")

saveRDS(index_meta, "index_meta.rds")
```

```{r, eval=T}
index_meta <- readRDS("index_meta.rds")

pretty_month_date <- function(x) {
  day <- mday(x)
  
  month <- snakecase::to_sentence_case(as.character(month(x,T,F,"English_Denmark.1252")))
  
  paste0(ifelse(wday(x) == 1, day, ""), ifelse(day == 7, paste0("\n", month), ""))
}

index_meta %>%
  # select(fid, src,Tag,Metadata) %>%
  filter(Tag != "SourceFile" & str_detect(absolute, "\\.JPG$")) %>%
  pivot_wider(c(fid,src), names_from=Tag, values_from = Metadata) %>%
  mutate(FileSize = as.integer(FileSize)) %>% 
  mutate(Time = ifelse(!is.na(CreateDate), CreateDate, FileCreateDate) %>% 
           ymd_hms %>% 
           as.Date) %>% 
  filter(src != "meta") %>% 
  ggplot(aes(Time,src)) +
  geom_point() +
  scale_x_date(labels = pretty_month_date,
               date_breaks = "1 day") +
  scale_color_brewer(palette = "Set1") +
  labs(x = "Date", y = "Image Series", title = "Image Annotations Chronology") +
  ggpubr::theme_pubr(base_family = "CMU Serif",
                     margin = F) +
  theme(title = element_text(face = "bold", size = 14),
        plot.title = element_text(face = "plain",
                                  hjust = .5,
                                  size = 18))
```
